spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.10.10.30:5432/pms
    username: pms
    password: pms
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: 10.10.10.30
      port: 6379
      password: usnQdkxCBP
  cloud:
    consul:
      host: 10.10.10.10
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        service-name: points